robot_parameters:
    base:
        #base params
        base_length: 0.3 #meters
        base_width: 0.18 
        base_height: 0.05
        base_density: 7850.0 #kg/m3
    wheel:
        wheel_radius: 0.04
        wheel_width: 0.02
        wheel_density: 900
    steering:
        max_steering_angle: 0.6108652 #radians
        max_steering_angular_velocity: 1.570796
        max_steering_effort: 1.0
        max_velocity: 2.0
        max_effort: 10
